config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('flights/', include('flights.urls'))
]

flights/urls.py
from django.urls import path
from . import views

app_name= 'flights'
urlpatterns = [
    path('', views.flights_list_view, name='list'),
    path('<int:flight_id>', views.flight_view, name='flight'),
    path('<int:flight_id>/book', views.book_view, name='book'),
]

flights/models.py
from django.db import models


# Create your models here.
class Airport(models.Model):
    city = models.CharField(max_length=50)
    code = models.CharField(max_length=3)

    def __str__(self):
        return f'{self.city} ({self.code})'


class Flight(models.Model):

    origin = models.ForeignKey(
        Airport, 
        on_delete=models.CASCADE,
        related_name = 'departures'
        )

    destination = models.ForeignKey(
        Airport, 
        on_delete=models.CASCADE,
        related_name = 'arrivals'
        )

    def __str__(self):
        return f'Flight {self.pk}: {self.origin} to {self.destination}'


class Passenger(models.Model):
    name = models.CharField(max_length=50)
    age = models.IntegerField()
    flights = models.ManyToManyField(Flight, related_name='passengers')

    def __str__(self):
        return f'{self.name} ({self.age})'
    
    

flights/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .models import Flight, Passenger
from django.urls import reverse

# Create your views here.
def flights_list_view(request):

    context = {'flights': Flight.objects.all()}
    return render(request, 'flights/list.html',context)


def flight_view(request, flight_id):

    f1 = Flight.objects.get(id=flight_id)
    passengers = f1.passengers.all()

    context = {
        'flight': f1,
        'passengers': passengers,
        'non_passengers': Passenger.objects.exclude(flights=f1.id)
        }

    return render(
        request, 
        'flights/eflight.html', 
        context
        )


def book_view(request, flight_id):
    if request.method == 'POST':

        passenger_id = int(request.POST['passenger_id'])

        passenger = Passenger.objects.get(id=passenger_id)
        flight = Flight.objects.get(id=flight_id)
        print('\n\npassenger: ', passenger)
        print('flight: ', flight)
        passenger.flights.add(flight)

        return HttpResponseRedirect(reverse('flights:flight', args=[flight.id,]))
    
            

flights/templates/flights/eflight.html
{% extends "flights/layout.html" %}

{% block main %}

<h1>Flight {{flight.id}}</h1>
<ul>
    <li>Origin: {{flight.origin}}</li>
    <li>Destination: {{flight.destination}}</li>
</ul>

<h2>Passengers</h2>

<ul>
    {% for passenger in passengers %}
    <li>{{passenger.name}}</li>
    {% endfor %}
</ul>

<h2>Book</h2>

<form action=" {% url 'flights:book' flight.id %}" method="POST">
    {% csrf_token %}
    <select name="passenger_id" id="">
        {% for non_passenger in non_passengers %}
        <option value="{{non_passenger.id}}">{{non_passenger}}</option>
        {% endfor %}
    </select>
    <input type="submit" value="Book flight">

</form>




<a href=" {% url 'flights:list' %}">Back to list of flights</a>
{% endblock main %}

flights/templates/flights/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flights</title>
</head>
<body>
    <main>
        {% block main %}
          
        {% endblock main %}
    </main>
</body>
</html>

flights/templates/flights/list.html
{% extends "flights/layout.html" %}

{% block main %}

<h1>List of Flights</h1>
<ul>
    {% for flight in flights  %}
    <li> 
        <a href=" {% url 'flights:flight' flight.id  %}"> {{flight}} </a>
    </li>
    {% endfor %}
</ul>

{% endblock main %}